name: Metrics

on:
  schedule:
    - cron: "30 2 * * *"   # run daily at 2:30 UTC
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Output file location
          filename: assets/imgs/metrics.svg

          # Template / base
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Chicago
          config_twemoji: yes

          # 🔥 Plugins
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_recent: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
